services:
  - type: web
    name: ff-pro-tournaments
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: DEVICE_OTP_SCRIPT_URL
        sync: false
      - key: RESET_PASS_SCRIPT_URL
        sync: false
      - key: CHALLENGE_UPLOAD_SCRIPT_URL
        sync: false


